/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uniguajira.matchsgame;

/**
 *
 * @author MARIA JOSE
 */
public class game_menu extends javax.swing.JFrame {

    /**
     * Creates new form game_menu
     */
    public game_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        TEMA = new javax.swing.JButton();
        TAMAÑO = new javax.swing.JButton();
        TIEMPO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TITULO.setBackground(new java.awt.Color(255, 0, 102));
        TITULO.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 51, 102));
        TITULO.setText("EMPAREJADOS");

        TEMA.setBackground(new java.awt.Color(255, 0, 102));
        TEMA.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        TEMA.setForeground(new java.awt.Color(255, 255, 255));
        TEMA.setText("TEMA");
        TEMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEMAActionPerformed(evt);
            }
        });

        TAMAÑO.setBackground(new java.awt.Color(255, 0, 102));
        TAMAÑO.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        TAMAÑO.setForeground(new java.awt.Color(255, 255, 255));
        TAMAÑO.setText("TAM-EMPAREJADO");
        TAMAÑO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMAÑOActionPerformed(evt);
            }
        });

        TIEMPO.setBackground(new java.awt.Color(255, 51, 102));
        TIEMPO.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        TIEMPO.setForeground(new java.awt.Color(255, 255, 255));
        TIEMPO.setText("TIEMPO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TITULO)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TEMA)
                        .addGap(18, 18, 18)
                        .addComponent(TAMAÑO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(TIEMPO)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAMAÑO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIEMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TEMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEMAActionPerformed
        System.out.println("tematicas:");        // TODO add your handling code here:
    }//GEN-LAST:event_TEMAActionPerformed

    private void TAMAÑOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMAÑOActionPerformed
        System.out.println("Escoja el tamaño del emparejado:");        // TODO add your handling code here:
    }//GEN-LAST:event_TAMAÑOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TAMAÑO;
    private javax.swing.JButton TEMA;
    private javax.swing.JButton TIEMPO;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
